name: github action CI

on:
  pull_request:
    branches:
      - main
      - testnet
  push:
    branches:
      - main
      - testnet

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
        cmd:
          - npm run compile
    name: Run on Node ${{ matrix.node }} env
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          path: ~/.npm
      - name: Install dependencies
        run: npm ci
      - name: ${{ matrix.cmd }}
        run: |
          ${{ matrix.cmd }}