name: github action CI

on:
  pull_request:
    branches:
      - main
      - testnet
  push:
    branches:
      - main
      - testnet

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20 ]
        cmd:
          - npm run compile
    name: Run on Node ${{ matrix.node }} env
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install dependencies
        run: npm i
      # https://github.com/crate-ci/typos/blob/master/docs/github-action.md
      - name: ${{ matrix.cmd }}
        run: |
          ${{ matrix.cmd }}