name: github action CI

on:
  pull_request:
    branches:
      - main
      - testnet
  push:
    branches:
      - main
      - testnet

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Test solidity contracts
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Compile contracts
        run: npm run compile
      - name: Test contracts
        run: npm run test